### ISSUE TITLE
Update "hosting a node" page to use go-ipfs

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/docs#191] opened 2021-11-19 20:14 UTC
* Remove instructions on using `@ceramicnetwork/ipfs-daemon` package
* Remove distinction about in-process vs out-of-process ipfs
* Include how to set up go-ipfs node with dag-jose support.
* Include link to js-ipfs -> go-ipfs migration guide from https://github.com/ceramicnetwork/docs/issues/192

**Comment by decentralgabe** [comment] 2022-01-06 16:41
duplicate of https://github.com/3box/ceramic-infra/issues/504

**Closed by decentralgabe** 2022-01-06 16:41 UTC
Labels: documentation
